/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PagesPokemonImport } from './routes/pages/pokemon'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PagesPokemonRoute = PagesPokemonImport.update({
  id: '/pages/pokemon',
  path: '/pages/pokemon',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pages/pokemon': {
      id: '/pages/pokemon'
      path: '/pages/pokemon'
      fullPath: '/pages/pokemon'
      preLoaderRoute: typeof PagesPokemonImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pages/pokemon': typeof PagesPokemonRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pages/pokemon': typeof PagesPokemonRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pages/pokemon': typeof PagesPokemonRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pages/pokemon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pages/pokemon'
  id: '__root__' | '/' | '/pages/pokemon'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesPokemonRoute: typeof PagesPokemonRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesPokemonRoute: PagesPokemonRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pages/pokemon"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pages/pokemon": {
      "filePath": "pages/pokemon.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
